### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [Shiv-Shambhu/Leaf-Explorer#4]
Could you please state which open-source license you chose to put your app under? There's none pointed out. I see several parts (see the editor) are taken from Bill who licensed his code under GPL3+ – so I assume the same applies to your app?

**Comment by mubashir-rehman** [comment]
Thanks for pointing it out. I think d3df60fc847f9db97dc526f587d5c116acb0d85a solves the issue.

**Comment by IzzySoft** [comment]
Thanks! Adjusted on my end (I've added your app [to my repo](https://apt.izzysoft.de/fdroid/index/apk/com.leaf.explorer) so potential users can discover and keep it updated more easy). IANAL, but doesn't GPLv3+ mean "3 or higher"? So can one use GPLv3+ libs in a GPLv2-only project? I also prefer GPLv2 and use it for most of my projects, and those license stuff always confuses me… It might well fit, as the general rule is "strictest policy on top, laxer ones can be inside" – and IIRC GPLv2 is stricter than GPLv3 :man_shrugging:

Feel free to close then if you agree :smiley: – and thanks again!

PS: If you want to link to your app in my repo (for easier install/update), be welcome to use [this badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it).
