### ISSUE TITLE
Give updated source code of Premium Version

### ISSUE THREAD

**Issue by mubashir-rehman** [Shiv-Shambhu/Leaf-Explorer#8]
### To Do:
Provide the source code of all(including latest i.e 1.15.40) versions of this app.
### Reason:
Most of the core components of this app are based upon the open source software. Those parts/libraries/pieces of code are available to you under GPLv2 or any later version or similar license. These licences require you to provide the same freedom to others as you got from them. This means providing the source code for free.
https://github.com/Shiv-Shambhu/Leaf-Explorer/blob/main/Version/V-1.15.40.MD#buy-source-code-v-11540 says that you are charging for source code of  an app build using FOSS works and is not legally correct.
### Suggestion:
In order to gain something out of your own efforts and work upon the existing FOSS works, you can opt to a model used by Retro Music player or Telegram.
Retro Music player has its complete source code available at https://github.com/RetroMusicPlayer/RetroMusicPlayer along with the in app purchases for themes. Your app can do the same by adding in-app purchases for the work you have done.
Telegram first releases its app and opens the source code after some time(a few days). This makes the users of telegram to use the official Telegram app instead of any other fork for faster updates. Even though they are obliged to provide source code on request from anyone, to which they provide the source code individually(of course free of cost).

**Comment by mubashir-rehman** [comment]
For reference Trebleshot explicitly stats that source code should always be provided to public even if used in commercial environment. https://github.com/trebleshot/android/blob/master/COPYING
![image](https://user-images.githubusercontent.com/51048830/127096025-876d6672-46b6-4cea-aaa5-45cea44532ec.png)

**Comment by Mahadev-code** [comment]
👍 Done

**Comment by mubashir-rehman** [comment]
Thanks a lot for your efforts and time. However, the license requires you to State Changes you made to original source which is usually done in the form git or any other version control system. I am closing this issue for now because you have provided the source code. I will create a new issue for request to provide the changes you made in some understandable form.
